language: java

dist: trusty

jdk:
- openjdk8

env:
  global:
  # GPG_KEYNAME=...
  - secure: "3IK/urilHkiD5I0Kwza8PuGWmf8LFmIRDHHEySn4mFazUBdN9RnfMSJDAmsxo0BXCvtR6MWi+3Vm71MKzEQqB4nuAh+clEUDqQg5XzY0+wZNhRZkdue/DkZX1lg/Ii/vo+dHlNPL7f6FK8IVERrIEoBh2S4kDrRaE0vIA4ErxFOwPkpX+VHQBfWIPvvlDh+vUU871wFUmzMyjBMeaukp8I1RJe6BJ4/olvbXEYAOd+XJx3f1UMZbAee0gGuoRqCF923W4RB8L3NhPn5mewpuCTCP5Eoj+Kcijt6NdvV9n3evRRWW9mKE1hQVRR3m2dwUzeOAXgnJOBr8NnFwzpxo/osicxbEvCPyZMfnOpGoSeNHORR8SbyvDbdUCQg2fsOEbfo2Rek5aEtW/+ksmwZ9zZVWKNZNW9nZjszFOz/bKC2UxeDecsjG/e8TKiZDjII9V9nwa24Jnykaih12Yhn4WMafgQJZZiHZVIvNBeLLQnelOlYFrltrlgAycYMPC1CkB5bJH5mv4E1rZZtWLq6I5ga+yzZ7FVm50H7MrxlrrIrq6IPyxYZJmSF+SerZ33T/Wz/awDqmqzFLn4fYqtF7RjyVnJR8kt6t6vAJhe6jyK5FDQuCtw9/kljLA1jh/UxYfdgO0olBaeZq8fl9rG5orNu4GwjX5Y4J0IUfTUKQKl8="
  # GPG_PASSPHRASE=...
  - secure: "oR2ZikrbTOF0X0VE1oJYCtA48QBJJoRilEx5eWr5nPiiRPk0x9n/S7OHUD8SPaiz+B1PSQjfltltAdQQWYTiYWXGM3emh6PhrO+u0ZNtnFroSHZeVHiJHA3d8qx9PUw1cUa3Rc1HGnJGDA8DhxisPGWg/0MlwUEl3HokVc8Ec2VLQzHWAye1eHlr9P4Ca1S0f7VeNq6gAZiAPWi39YGhG4ZWV8gqpAvqOcJPdlKVUdT/U/6+47Pvrp7EzASapXLODLMbkiGREtdbu8+UiylpCmuLfD74aipbNjIbcew9TY0Vvy86yxUkEEyM08yAic7QXxEYYDx5TkkR1pBEX+BP/UustjanlsCLSrBpOXjOYENytiI0hgHjLFFuLi+mmmhbKn29s+w12AhVFjurc8iXsLWKgfbZJRwbw1x5yFyJBvkSO6YO4Jd/3K38vrbzwZaPi7g2iv+yCSOGERy4daGDS16N88vzQrIhL47J0g/VV7lYE7zWl0DtIpVu9OJRGyM43zj92e5bfCgHQxXD5EnrZ5G2JXoPFDYZxhhOI2EUg/gqx2DMbKmZn0PP6K0EuH9DuZBQKGHbg6kVfIEdR/DwAakT/PoZEw7NuWgY31UJY9MyGwEQB2gpCrB0VmlP8BYzcp6T2V2OsMMMU3dYBVVWfbQgOPUuXPHOxQuR1EFsywQ="
  # SONATYPE_USER=...
  - secure: "iDCv/HpFWz76UKBLfpCT+QNBhpypFkz5lwTRzIOcjLBmGfyadY2TA3A5OHdggJ29/qVbWfvNyU8x+RkfcFAlzdF1SkVSD2kVMyN3AIll56pPK5V/JWmKL+/nIOP5r6/0cw6tGUajBiRgVDd6pgXwNMEn3B8W5um52IDzUnjOukXavQOjq00vI5P1G1B889kGRmBj5RRNzF2crfQKY0R+USTyx8KMFQcTqDBKd4ENddDM2FGxJyJyLboEMrV0e/J+EIikR5WalZhHzEZUfenFBigwdDGc3opUveYvKP2wy3zX/VC3jFiJaq6MfcORpVqsoCov/Ej5gGEeFCXhmxP2X/rf1MkHJtLQKqjN8Krx9cxGQw4MQECDjnFTaufADk97yP4zHfzXgwSymywWmzDduDmLNMt4LX22WFzPcXtF3TjJU5ytsbWy9kfqWrQXJTt2ftDF2AtfSigtFderTnR9A0teE4gNj9vf3IuWU7QT7ufSl+L+QKXIhrC+2zXXV7ZkN16WJaWq86OOANEbEbY+dm9XwBgrz7DtjEfNblKaxr7olRALssq+wEpwokcX+K+o4ND/N25rIs1k5yeNKj8v+aG8gaHwJdhZ/YebZh/Ed1JEUCn9psCMeaCKCiKkT61ZgVOqdkPiU2z862ArmhpUarbD6aT0TVJb2P9Yp8UOAhs="
  # SONATYPE_PASSWORD=...
  - secure: "ZhbxreetLr7q3RMGVoaKmKIrPIc3TGm1/itM31yP22ngUku9wEOArjxZpJN7LpBwSCN2YKRCvN/sFyR8ko39MHG2wT9YiH8alXxDFu4pvojSRuZeGQtJdGnD17ssbYcKY38cMy6JHEe5FFd/aWaoBTBmlA/FnkrXl2NbluWfvCVE4YNXAphogTnoYZYYzyAStLJZsAhwrCXkOp+Ml2fDI2tO9VbwYF0MYwEke6sx0oiUJfe6yaNnfz1BWtDrI98vr2oyT0ZAgwe0S1KRfJrlj7+cCp3WzIo+f65/ebVXVCZYIheCbPkQInD9pENVKI6Q5vkjrn9O7AKp4KCG2vZGv6Z/kfmaoixBAujayG2j1ibAdRQxOtW60EYPCFLTP6dvtO4rHN73KuFA35ifK2tXnr/2Pzu4+ZFJBsVP4yMhzbODBiErcc4H01MxT6INN0lgBsYwBRNarO6o1sgPEs1ARP99k5XB8Pf0Lx+fiOHQrIcsUrAjSUFc62XEjJ2oNGSXb9QECtF7MZ4GJm2w7Wkufg3WP5pz0NpElUCCJnfZqMGCUAgwIytdQtHknWLDM6coCNrd1iOY4EcsudE3u9jA/NTq2Akp2SB0LylFIg9JNgHA7DfCRhbXKd2qmBVntPtblyFJlBuYSFw1TRjM0s6fWWU80PMnpQ4MrTp9OljaWQM="

install:
- openssl aes-256-cbc -K $encrypted_c0a16ba7f391_key -iv $encrypted_c0a16ba7f391_iv -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar

script:
- if [[ ! -z $TRAVIS_TAG ]]; then mvn versions:set -DnewVersion=$TRAVIS_TAG; fi
- mvn -B -Ptravis --settings .m2/settings.xml clean deploy

cache:
  directories:
  - "$HOME/.m2/repository"
